version: '3.8'
services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - TZ=Asia/Krasnoyarsk
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - TZ=Asia/Krasnoyarsk
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  db:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=Asia/Krasnoyarsk