version: '3.8'
services:
  gateway:
    build:
    image:
    container_name:
    ports:
      - "8080:8080"
    depends_on:
    environment:
      - TZ=Asia/Krasnoyarsk
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build:
    image:
    container_name:
    ports:
      - "9090:9090"
    depends_on:
    environment:
      - TZ=Asia/Krasnoyarsk
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  db:
    image:
    container_name:
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=Asia/Krasnoyarsk